name: Docker image build

on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the short sha
        id: short_sha
        run: echo ::set-output name=SHA::$(echo $GITHUB_SHA | cut -c1-8)
      - run: echo $TAG
        env:
          TAG: ${{ steps.short_sha.outputs.SHA }}
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{ env.GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: docker.pkg.github.com/modrinth/labrinth/labrinth
          tag_with_ref: true
          tag_with_sha: true